# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d1c66d2e34166ea2036c0a290311ab7523cb8a5216ed2df1e6bdd3278a9f008c44a9df0bb872ea97d33a914213060ba3ec7dd35c0212bef7b2e300fa7e48a1b

test:
  secret_key_base: 45d0321756f410279c1c638afd236a246d7b5475d27e4563a942b929721f7844093c2894a9abb138a63e9d5cb32e9ff25b7313484658b713181894c32ae35129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
